### ISSUE TITLE
Incompatiblity with CF diego release

### ISSUE THREAD

**Issue by vvraskin** [cloudfoundry-community/node-cfenv#11]
Hello,

Recently we have tested our "HelloWorld" nodejs apps on the diego part of CF. As can be followed from the release notes https://github.com/cloudfoundry-incubator/diego-design-notes, several env variables inside of containers were deprecated. 

The call of 'cfenv.getAppEnv' causes the following error: 'Error: cfenv: expecting VCAP_APPLICATION to contain uris when not runninng locally'

Could you please test the code on diego or let me know if I can somehow help here?

Thanks in advance.

Regards, 
Vadim

**Comment by pmuellr** [comment]
> Could you please test the code on diego or let me know if I can somehow help here?

I don't have a clue as to how I would test on diego.  I'm not set up to run a CF install.  If there's a Docker image that just runs, zero setup time, that I can test with - or something similar - let me know.  Or is anyone running some kind of a sandbox live?

With regard to the changes, I guess this is the relevant info?

* [cloudfoundry-incubator/diego-design-notes/migrating-to-diego.md](https://github.com/cloudfoundry-incubator/diego-design-notes/blob/a582441a3e0110fc389af9c9571ecfdc33610ab3/migrating-to-diego.md#cf-specific-environment-variables)

Looks like we can make a fix here: [lib-src/cfenv.coffee](https://github.com/cloudfoundry-community/node-cfenv/blob/master/lib-src/cfenv.coffee#L189)

Something like from:

```coffee-script
uris = appEnv.app?.uris
```

to:

```coffee-script
uris = appEnv.app?.uris || []
```

Might work.  Wanna give it a try?

The equivalent line in the js file, if you don't want to futz with a build, and just whack it to try it, is here: [lib/cfenv.js](https://github.com/cloudfoundry-community/node-cfenv/blob/master/lib/cfenv.js#L246)

That change would be something like from:

```js
uris = (ref = appEnv.app) != null ? ref.uris : void 0;
```

to:

```js
uris = (ref = appEnv.app) != null ? ref.uris : [];
```

**Comment by pmuellr** [comment]
Not a breaker, but will also want to change the reference of `VCAP_APP_PORT` to `CF_INSTANCE_PORT`.  That's why you should **always** use the `PORT` environment variable (he says, wiping his brow, thankful they didn't deprecate the `PORT` environment variable).

**Comment by pmuellr** [comment]
@vvraskin - I have a branch for you to try.  In your `package.json` dependencies, use the following instead of the `cfenv` version number:

```text
cloudfoundry-community/node-cfenv#pmuellr/issue-11
```

You can also use that from the command-line, to install locally, without referencing your `package.json`:

```text
npm install cloudfoundry-community/node-cfenv#pmuellr/issue-11
```

Let me know if it works, I'll push it up to npm as a new version.

**Comment by vvraskin** [comment]
I've checked my code with the updated version of cfenv on Diego, it seems to be working fine.
So you may push it to npm. 

Could you please let me know once you do that.

Thanks.

**Comment by pmuellr** [comment]
@vvraskin - npm has been updated to 1.0.3

**Comment by pmuellr** [comment]
closing as I believe this has been resolved
