### ISSUE TITLE
Incorrect app url returned for https protocol

### ISSUE THREAD

**Issue by prachikhadke** [cloudfoundry-community/node-cfenv#18]
Running the following:

    var cfenv = require("cfenv")
    var appEnv = cfenv.getAppEnv({protocol: "https"});

get `url: "https//localhost:6001"` in the returned appEnv instead of `url: "https://localhost:6001"`

**Comment by pmuellr** [comment]
That is the correct behavior.

From the README, last bit bolded for emphasis:

> * `protocol` - protocol used in the generated URLs
>
> This value is to override the default protocol used when generating the URLs in the returned object. It should be the same format as node's url protocol property. **That is, it should end with a : character.**
