### ISSUE TITLE
getServiceURL break url

### ISSUE THREAD

**Issue by melnikaite** [cloudfoundry-community/node-cfenv#21]
`console.log(appEnv.getServiceURL('mongodb-instance'));`

`console.log(appEnv.getService('mongodb-instance').credentials.uri);`

`mongodb://admin:XXX@sl-us-dal-9-portal.4.dblayer.com:18394/:18394,sl-us-dal-9-portal.1.dblayer.com/admin?ssl=true`

`mongodb://admin:XXX@sl-us-dal-9-portal.4.dblayer.com:18394,sl-us-dal-9-portal.1.dblayer.com:18394/admin?ssl=true`

**Comment by pmuellr** [comment]
Ah, yikes!  smells like url.parse() shenanigans, since I just ran into something very similar in a different set of code.

Thanks for reporting!

**Comment by melnikaite** [comment]
It'd be nice to have this fix in `1.0.4`.
Are there any plans to make new release?

**Comment by pmuellr** [comment]
@melnikaite sorry, was waiting for a review in the 1.0.4 PR https://github.com/cloudfoundry-community/node-cfenv/pull/23 .  Ping'd reviewer again, will update tomorrow if I haven't heard back.

**Comment by pmuellr** [comment]
@melnikaite there's now a fresh 1.0.4 up on npm
