### ISSUE TITLE
no instructions how to use cfenv in angular5 app deployed in the cloud foundry the angular app is deployed in the node.js runtime environment in the cloud (pitoval cloud foundry)

### ISSUE THREAD

**Issue by osujii191** [cloudfoundry-community/node-cfenv#32]
no instructions how to use cfenv in angular5 app deployed in the cloud foundry, the angular app is deployed in the node.js runtime environment in the cloud (pushed angular app on to the cloud using pitoval cloud foundry - nodejs runtime)

**Comment by osujii191** [comment]
i am using this in a node.js runtime and still don't understand how to use it.

**Comment by osujii191** [comment]
when i checked the instructions on the npmjs.com i see the following: 
"This means you can use this package in your program and it will provide useful values when you're running in Cloud Foundry AND **when you're running locally.**"...unable to use this library locally

**Comment by osujii191** [comment]
Also see below error ;
$ npm install @ types/cfenv --save
npm ERR! code E404
npm ERR! 404 Not Found: @ types/cfenv@ latest

**Comment by pmuellr** [comment]
I'm not surprised the command below failed; it would require someone to add that package - `@types/cfenv` - to npm, and I guess no one has.

```
$ npm install @ types/cfenv --save
```

Feel free to do so yourself.

**Comment by pmuellr** [comment]
The [README](https://github.com/cloudfoundry-community/node-cfenv) explains how to use the package.  I'm not sure what you don't understand, so can't really help you.

Please be more specific.  What are you trying to do?

**Comment by pmuellr** [comment]
Closing due to lack of feedback.
