### ISSUE TITLE
Can't get `cf files` with Diego backend

### ISSUE THREAD

**Issue by FMGordillo** [cloudfoundry-community/node-cfenv#35]
Trying to get `bx cf files <app-name> logs/env.log`

```
FAILED
The app is running on the Diego backend, which does not support this command.
```

So how do we proceed [this part](https://github.com/cloudfoundry-community/node-cfenv/tree/master/sample-data) of the repo?

**Comment by pmuellr** [comment]
I have no idea what `bx cf files <app-name> logs/env.log` is supposed to do, so ... please describe it, or point to docs.

It would also help to describe what problem you are seeing with `cfenv`, in this case, since it's not clear.

**Comment by pmuellr** [comment]
closing as it's inactive
