### ISSUE TITLE
add a cli tool to launch local app with VCAP_SERVICES from cf app

### ISSUE THREAD

**Issue by pmuellr** [cloudfoundry-community/node-cfenv#4]
To make life easier when running apps locally, it would be nice to have a cli tool which you could use to launch an app, and have the VCAP_SERVICES env var from the app running in Cloud Foundry set in the local launch.

Basic idea is this:
- determine app name from `manifest.yml`
- run `cf env {appName}`
- capture `VCAP_SERVICES` entry
- launch command specified as arguments to the cli tool, with the `VCAP_SERVICES` env var set to what came back from `cf env`

**Comment by pmuellr** [comment]
current work in branch `cf-env-launch`

**Comment by srl295** [comment]
// cc @ryanj

**Comment by pmuellr** [comment]
After seeing this again after ~2 years, seems like it's good fodder for a separate npm package, rather than including it here.  Pretty much has nothing to do with what cfenv does today.

Closing, but could be convinced to re-open with a good argument for it.

**Comment by srl295** [comment]
Makes sense
