### ISSUE TITLE
.env file support ?

### ISSUE THREAD

**Issue by DivekJohns** [cloudfoundry-community/node-cfenv#44]
Hi folks,
Any workaround to use .env files for this library?

**Comment by pmuellr** [comment]
> Any workaround to use .env files for this library?

You'll need to provide more context.  Not sure how or when you would expect a .env file to be used.  For local testing?

**Comment by DivekJohns** [comment]
> > Any workaround to use .env files for this library?
> 
> You'll need to provide more context. Not sure how or when you would expect a .env file to be used. For local testing?

Problem: I have many environments [local, stage, production]
It is very challenging to connect to these environments to debug locally, we end up hardcoding values, so thought of maintaining multiple .env files for different environments and load according to NODE_ENV. 
I recently came through vcap file, it would be a great help if some snippet demonstrates how VCAP file should be used, please !
