### ISSUE TITLE
getServices(spec) ?

### ISSUE THREAD

**Issue by srl295** [cloudfoundry-community/node-cfenv#7]
`getServices()` returns all services.

Could it take an optional `spec` parameter with a regex?

Then if I bind against a bunch of `MyService-abc`, `MyService-bcd`, ... I can do `getServices(/MyService-.*/)` to use a user-provided service to set a list.

**Comment by pmuellr** [comment]
That seems like it makes sense; it would be extending the functionality of `getServices()`, and fills a niche of finding services that match some kind of spec.  Should it be the same kind of spec as `getService()`?

**Comment by srl295** [comment]
Yes, I'd think the same kind of spec.

**Comment by pmuellr** [comment]
I guess it would be useful for you to see if just filtering the result is easy enough.  See https://tonicdev.com/pmuellr/get-services-spec for an example of filtering the results with `underscore.pick()`.  

Here's the code from the tonic:

```js
const us = require("underscore")

const services = {a:"1", b:"2", c:"3"}

console.log(us.pick(services, (val,key)=>key.match(/a|b/)))
console.log(us.pick(services, ["b", "c"]))
```

I don't really have the cycles for this.  If someone does want to add it, submit a PR:

* code should be in existing style
* update the doc
* add test cases
* squash PR to a single commit (be prepared to squash more if more changes are required)

**Comment by srl295** [comment]
@pmuellr looks easy enough wiht `pick()`, thanks.
